/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.enrollmentsystem;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rcaraos
 */
public class StudentsForm extends javax.swing.JFrame {
    
    public void showrecords(){
        DefaultTableModel tblmodel = (DefaultTableModel) studTable.getModel(); //instatiation
        tblmodel.setRowCount(0);
        EnrollmentSystem db = new EnrollmentSystem();
        db.DBConnect();
        try{
            String query = "SELECT * FROM students";
            db.rs = db.st.executeQuery(query);
            System.out.printf("Success with SQL");
        while (db.rs.next()){
            String i = db.rs.getString("studid");
            String c = db.rs.getString("studname");
            String d = db.rs.getString("studadd");
            String t = db.rs.getString("studcrs");
            String g = db.rs.getString("studgender");
            String y = db.rs.getString("studyrlvl");
            String [] item = {i,c,d,t,g,y};
            tblmodel.addRow(item);
        }  
     
        }
        catch(Exception ex){
            System.out.print("unsuccessfull");
        }
    }
    
   
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentsForm.class.getName());

    /**
     * Creates new form StudentsForm
     */
    public StudentsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        savebut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studTable = new javax.swing.JTable();
        delbut = new javax.swing.JButton();
        editbut = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        searchlabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        open = new javax.swing.JMenu();
        edit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        savebut.setText("Save");
        savebut.addActionListener(this::savebutActionPerformed);

        studTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Adress", "Course", "Gender", "Year"
            }
        ));
        jScrollPane1.setViewportView(studTable);

        delbut.setText("Delete");
        delbut.addActionListener(this::delbutActionPerformed);

        editbut.setText("Edit");
        editbut.addActionListener(this::editbutActionPerformed);

        search.addActionListener(this::searchActionPerformed);

        searchlabel.setText("Search");

        open.setText("Open");
        jMenuBar1.add(open);

        edit.setText("Edit");
        jMenuBar1.add(edit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(savebut)
                .addGap(66, 66, 66)
                .addComponent(editbut)
                .addGap(79, 79, 79)
                .addComponent(delbut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchlabel))
                .addGap(220, 220, 220))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchlabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editbut)
                    .addComponent(savebut)
                    .addComponent(delbut))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savebutActionPerformed

    private void delbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delbutActionPerformed

    private void editbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editbutActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentsForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delbut;
    private javax.swing.JMenu edit;
    private javax.swing.JButton editbut;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu open;
    private javax.swing.JButton savebut;
    private javax.swing.JTextField search;
    private javax.swing.JLabel searchlabel;
    private javax.swing.JTable studTable;
    // End of variables declaration//GEN-END:variables
}
