/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.enrollmentsystem;

import static com.mycompany.enrollmentsystem.StudentsForm.okcancel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rcaraos
 */
public class TeachersForm extends javax.swing.JFrame {
    String teachid;
    String teachname;
    String teachdept;
    String teachcontact;
    String teachadd;
    String teachstats;
    
public void showRecords(){
        DefaultTableModel tblmodel = (DefaultTableModel) teachTable.getModel();
        tblmodel.setRowCount(0);
        EnrollmentSystem b = new EnrollmentSystem();
       
        b.DBConnect();
        
        String searchText = search2.getText();
        if (searchText.equals("Search")) searchText = ""; 
        
        try{
            String query = "select * from Teachers where concat(tid, tname, tdept, tadd, tcontact, tstatus) like '%" + searchText + "%'";
            b.rs = b.st.executeQuery(query);
            System.out.println("Success with sql!");  
            
            while (b.rs.next()){
                String i = b.rs.getString("tid");
                String c = b.rs.getString("tname");
                String d = b.rs.getString("tdept");
                String g = b.rs.getString("tadd");
                String f = b.rs.getString("tcontact");
                String h = b.rs.getString("tstatus");
                String[] items = {i,c,d,g,f,h};
                tblmodel.addRow(items); //array
            }
        }catch (Exception ex){
            System.out.print("not Success with sql! teachers");
             ex.printStackTrace();
        }
        showAssign();
    }

 private void showAssign(){
    DefaultTableModel tblmodel = (DefaultTableModel) assignTable.getModel();
    tblmodel.setRowCount(0);
    EnrollmentSystem b = new EnrollmentSystem();
    b.DBConnect();
    
    // Check if the student ID is actually correct
    System.out.println("--- STARTING SHOW ASSIGN ---");
    System.out.println("Target Teacher ID (teachid): " + teachid);
    
    try {
        String query = "select * from subjects where subjid in(select subjid from assign where tid = " + teachid + " )";
        System.out.println("Query being executed: " + query);
        
        b.rs = b.st.executeQuery(query);
        
        int rowCount = 0;
        while (b.rs.next()) {
            rowCount++;
            System.out.println("Found subject row " + rowCount + " in database...");
            
            // If it fails on any of these lines, your column names are wrong
            String i = b.rs.getString("subjid");
            String c = b.rs.getString("subjcode");
            String d = b.rs.getString("subjdesc");
            int t = b.rs.getInt("subjunits"); 
            String g = b.rs.getString("subjsched");
            
            Object[] items = {i, c, d, t, g}; 
            tblmodel.addRow(items);
            System.out.println("Successfully added subject: " + c + " to GUI table.");
        }
        
        System.out.println("Total rows fetched and added: " + rowCount);
        if (rowCount == 0) {
            System.out.println("WARNING: Database query successful, but returned 0 rows.");
        }
        
    } catch (Exception ex) {
        System.out.println("--- EXCEPTION CAUGHT IN SHOWASSIGN ---");
        ex.printStackTrace();
    }
        }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TeachersForm.class.getName());

    /**
     * Creates new form Teachers
     */
    public TeachersForm() {
        initComponents();
        showRecords();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        teachTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        tname = new javax.swing.JTextField();
        tdept = new javax.swing.JTextField();
        tcontact = new javax.swing.JTextField();
        search2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        deleteBtn2 = new javax.swing.JButton();
        saveBtn2 = new javax.swing.JButton();
        editBtn2 = new javax.swing.JButton();
        tadd = new javax.swing.JTextField();
        tstatus = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        AssignBtn = new javax.swing.JButton();
        DropBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        assignTable = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        teachTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Department", "Address", "Contact", "Status"
            }
        ));
        teachTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teachTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(teachTable);
        if (teachTable.getColumnModel().getColumnCount() > 0) {
            teachTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TEACHERS' DASHBOARD");

        jLabel9.setText("ID");

        jLabel10.setText("Name");

        jLabel11.setText("Department");

        jLabel13.setText("Contact");

        tid.setEnabled(false);
        tid.addActionListener(this::tidActionPerformed);

        tname.addActionListener(this::tnameActionPerformed);

        search2.setText("Search");
        search2.setToolTipText("");
        search2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                search2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                search2FocusLost(evt);
            }
        });
        search2.addActionListener(this::search2ActionPerformed);
        search2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                search2KeyPressed(evt);
            }
        });

        deleteBtn2.setBackground(new java.awt.Color(204, 102, 255));
        deleteBtn2.setForeground(new java.awt.Color(0, 0, 0));
        deleteBtn2.setText("Delete");
        deleteBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteBtn2MousePressed(evt);
            }
        });
        deleteBtn2.addActionListener(this::deleteBtn2ActionPerformed);

        saveBtn2.setBackground(new java.awt.Color(204, 102, 255));
        saveBtn2.setForeground(new java.awt.Color(0, 0, 0));
        saveBtn2.setText("Save");
        saveBtn2.addActionListener(this::saveBtn2ActionPerformed);

        editBtn2.setBackground(new java.awt.Color(204, 102, 255));
        editBtn2.setForeground(new java.awt.Color(0, 0, 0));
        editBtn2.setText("Edit");
        editBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtn2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(deleteBtn2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBtn2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editBtn2)
                .addGap(46, 46, 46))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn2)
                    .addComponent(deleteBtn2)
                    .addComponent(editBtn2)))
        );

        jLabel14.setText("Status");

        jLabel15.setText("Address");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(search2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tdept, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                .addComponent(tname, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tid, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tcontact)
                                .addComponent(tadd, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(15, 15, 15))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(search2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tdept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel12.setText("ASSIGNED SUBJECTS");

        AssignBtn.setText("Assign Subject");
        AssignBtn.addActionListener(this::AssignBtnActionPerformed);

        DropBtn.setText("Drop Subject");
        DropBtn.addActionListener(this::DropBtnActionPerformed);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(AssignBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(DropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AssignBtn)
                    .addComponent(DropBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        assignTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "SubID", "SubCode", "SubDescription", "SubUnits", "SubSchedule"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        assignTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assignTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(assignTable);

        jMenu3.setText("Open");

        jMenuItem3.setText("Students");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Subjects");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu3.add(jMenuItem4);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane4)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(224, 224, 224)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addComponent(jLabel12))
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(225, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(128, 128, 128)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(371, 371, 371)
                    .addComponent(jLabel12)
                    .addGap(18, 18, 18)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(203, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // TODO add your handling code here:


    private void tnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnameActionPerformed

    private void teachTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teachTableMouseClicked
        int selectedRow = teachTable.getSelectedRow();

        if (selectedRow < 0) return;

        teachid = (String) teachTable.getValueAt(selectedRow, 0);
        tid.setText(teachid);

        teachname = (String) teachTable.getValueAt(selectedRow, 1);
        tname.setText(teachname);

        teachdept = (String) teachTable.getValueAt(selectedRow, 2);
        tdept.setText(teachdept);
        
        teachadd = (String) teachTable.getValueAt(selectedRow, 3);
        tadd.setText(teachadd);

        teachcontact = (String) teachTable.getValueAt(selectedRow, 4);
        tcontact.setText(teachcontact);
       
        teachstats = (String) teachTable.getValueAt(selectedRow, 5);
        tstatus.setText(teachstats);

       showAssign();
    }//GEN-LAST:event_teachTableMouseClicked

    private void tidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidActionPerformed

    private void tname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tname1ActionPerformed

    private void search2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search2FocusGained
        if (search2.getText().equals("Search")) {
            search2.setText("");
        }
    }//GEN-LAST:event_search2FocusGained

    private void search2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search2FocusLost
        if (search2.getText().trim().isEmpty()) {
            search2.setText("Search");
        }
    }//GEN-LAST:event_search2FocusLost

    private void search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search2ActionPerformed

    private void search2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search2KeyPressed
        showRecords();
    }//GEN-LAST:event_search2KeyPressed

    private void deleteBtn2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtn2MousePressed

    }//GEN-LAST:event_deleteBtn2MousePressed
    private void messagebox(String msg, String titlebar){
     JOptionPane.showMessageDialog(null,msg,titlebar,JOptionPane.INFORMATION_MESSAGE);   
     } 
    
    private void deleteBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn2ActionPerformed
        Teachers b = new Teachers();
        if ("".equals(tid.getText()) )
        messagebox("Select a Teacher to Delete first","Delete");
        else
        b.delete_teacher(Integer.parseInt(tid.getText()));

        showRecords();
    }//GEN-LAST:event_deleteBtn2ActionPerformed

    private void saveBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtn2ActionPerformed
        Teachers c = new Teachers();
        c.newteacher (
            tname.getText(),
            tdept.getText(),
            tadd.getText(),
            tcontact.getText(),
            tstatus.getText());
        showRecords();
    }//GEN-LAST:event_saveBtn2ActionPerformed

    private void editBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtn2MouseClicked

        Teachers c = new Teachers();

        if ("".equals(tid.getText()) )
        messagebox("Select a Teacher to Update first:","Update");
        else
        c.update_Teacher(
            tname.getText(),
            tdept.getText(),
            tadd.getText(),           
            tcontact.getText(),           
            tstatus.getText()
                   );
        showRecords();

    }//GEN-LAST:event_editBtn2MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      StudentsForm a = new StudentsForm();
      a.setVisible(true);
      
      a.showRecords();   
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
      SubjectsForm a = new SubjectsForm();
      a.setVisible(true);
      
      a.showRecords(); 
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void DropBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropBtnActionPerformed
       Assign a = new Assign();
        
        String result = a.deleteSubject(Integer.parseInt(teachid));
        
        if (result.equals("Drop Failed")) {
        messagebox(result, "Drop Failed");
        } else if (result.equals("Teacher is not assigned to this subject.")) {
        messagebox(result, "Drop Failed");
        } else {
        messagebox(result, "Success!!");
        }
        showAssign();
        
    }//GEN-LAST:event_DropBtnActionPerformed

    private void AssignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignBtnActionPerformed
        Assign a = new Assign();
        
        if (a.getsubjid() == 0) {
        messagebox("Please select a subject first.", "Assign");
        return;
    }
        int i = okcancel("Assign Teacher ID:" + teachid + " to subject ID:" +  a.getsubjid());
        if (i == 0) {
            String result = a.assignTchr(Integer.parseInt(teachid));
            if (result.equals("Teacher is already assigned to this subject.")) {
                messagebox(result, "Assignment Failed");
            } else {
                messagebox(result, "Success!!");
                showAssign();
            }
        } else {
            messagebox("Cancel Assign " + teachid, "Assign");
        }
    }//GEN-LAST:event_AssignBtnActionPerformed

    private void assignTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignTableMouseClicked
     Assign a = new Assign();
    int selectedRow = assignTable.getSelectedRow();

    if (selectedRow != -1) {
        int selectedSubjid = Integer.parseInt(
                assignTable.getValueAt(selectedRow, 0).toString()
        );

        System.out.println("Selected Subject ID: " + selectedSubjid);

        a.setsubjid(selectedSubjid);
    }
    }//GEN-LAST:event_assignTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TeachersForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignBtn;
    private javax.swing.JButton DropBtn;
    private javax.swing.JTable assignTable;
    private javax.swing.JButton deleteBtn2;
    private javax.swing.JButton editBtn2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton saveBtn2;
    private javax.swing.JTextField search2;
    private javax.swing.JTextField tadd;
    private javax.swing.JTextField tcontact;
    private javax.swing.JTextField tdept;
    private javax.swing.JTable teachTable;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tstatus;
    // End of variables declaration//GEN-END:variables
}
