package com.mycompany.enrollmentsystem;

import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

/**
 *
 * @author rcaraos
 */
public class Teachers {
 
public void newteacher(String tname, String tdept, String tadd, String tcontact, String tstatus) {

    EnrollmentSystem b = new EnrollmentSystem();
    b.DBConnect();

    try {

        // Check if Teachers table is empty
        String checkQuery = "SELECT COUNT(*) FROM Teachers";
        ResultSet rs = b.st.executeQuery(checkQuery);

        int count = 0;

        if (rs.next()) {
            count = rs.getInt(1);
        }

        // If table is empty, start ID at 3000
        if (count == 0) {
            b.st.executeUpdate(
                "ALTER TABLE Teachers AUTO_INCREMENT = 3000"
            );
        }

        // tid is automatically generated by MySQL
        String query = "INSERT INTO Teachers " +
                       "(tname, tdept,tadd, tcontact,tstatus) VALUES ('" +
                       tname + "', '" +
                       tdept + "', '" +
                       tadd + "', '" +
                       tcontact + "', '" +
                       tstatus + "')";

        int rows = b.st.executeUpdate(query);

        if (rows > 0) {
            System.out.println("Teacher Added successfully!");
        }

    } catch (Exception ex) {
        System.out.println("Not successful! (Teacher)");
        ex.printStackTrace();
    }
}

    
    public void delete_teacher(int tid){
        EnrollmentSystem b = new EnrollmentSystem();
    b.DBConnect();
    String query = "delete from Teachers where tid ="+ tid;
    try {
            int rows = b.st.executeUpdate(query);
        }
    catch(Exception ex) {
        System.out.println("Not successful! (Teacher)");
        ex.printStackTrace();
    }
   
    }
    public void update_Teacher( String tname, String tdept, String tadd, String tcontact, String tstatus){
    EnrollmentSystem b = new EnrollmentSystem();
    b.DBConnect();
    String query = "UPDATE teachers SET tname = ?, tdept = ?, "
                 + "tcontact = ? WHERE tid = ?";
    try {
        java.sql.PreparedStatement ps = b.con.prepareStatement(query);
        ps.setString(1, tname);
        ps.setString(2, tdept);
        ps.setString(3, tadd);
        ps.setString(4, tcontact);
        ps.setString(5, tstatus);
       
        int rows = ps.executeUpdate();
        if (rows > 0) {
            System.out.println("Teacher updated successfully!");
        }
    } catch(Exception ex) {
        System.out.println("Not successful!");
        ex.printStackTrace();
    }
}
}